// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGudtrC4e4aMJMwzS2zJEJHRJQkV-CKik',
    appId: '1:791336479518:web:4303365fb9a63eea33370f',
    messagingSenderId: '791336479518',
    projectId: 'water-reminder-app-4299b',
    authDomain: 'water-reminder-app-4299b.firebaseapp.com',
    databaseURL: 'https://water-reminder-app-4299b-default-rtdb.firebaseio.com',
    storageBucket: 'water-reminder-app-4299b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpOXUZ5tpVPv6wC7A-tHA-4zn0eO_527s',
    appId: '1:791336479518:android:0a043f112d1011c333370f',
    messagingSenderId: '791336479518',
    projectId: 'water-reminder-app-4299b',
    databaseURL: 'https://water-reminder-app-4299b-default-rtdb.firebaseio.com',
    storageBucket: 'water-reminder-app-4299b.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGudtrC4e4aMJMwzS2zJEJHRJQkV-CKik',
    appId: '1:791336479518:web:5f164157543639a733370f',
    messagingSenderId: '791336479518',
    projectId: 'water-reminder-app-4299b',
    authDomain: 'water-reminder-app-4299b.firebaseapp.com',
    databaseURL: 'https://water-reminder-app-4299b-default-rtdb.firebaseio.com',
    storageBucket: 'water-reminder-app-4299b.appspot.com',
  );
}
